default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_explorer_development

test:
  <<: *default
  database: book_explorer_test

production:
  <<: *default
  database: book_explorer_production
  username: book_explorer
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
